/*기본정보 입력*/

INSERT INTO `kakaobank`.`BASE_CODE_MASTER` (`CODE_GROUP_ID`, `BASE_CODE_VALUE`, `CODE_NAME`) VALUES ('ACCT_MANG_BASE_CODE', '00', '정상');
INSERT INTO `kakaobank`.`BASE_CODE_MASTER` (`CODE_GROUP_ID`, `BASE_CODE_VALUE`, `CODE_NAME`) VALUES ('ACCT_MANG_BASE_CODE', '99', '폐쇄');
INSERT INTO `kakaobank`.`BASE_CODE_MASTER` (`CODE_GROUP_ID`, `BASE_CODE_VALUE`, `CODE_NAME`) VALUES ('ACCT_MANG_BASE_CODE', '98', '사고계좌');
INSERT INTO `kakaobank`.`BASE_CODE_MASTER` (`CODE_GROUP_ID`, `BASE_CODE_VALUE`, `CODE_NAME`) VALUES ('TRNS_BASE_CODE', '01', 'WU빠른송금');
INSERT INTO `kakaobank`.`BASE_CODE_MASTER` (`CODE_GROUP_ID`, `BASE_CODE_VALUE`, `CODE_NAME`) VALUES ('TRNS_BASE_CODE', '02', '해외일반송금');

INSERT INTO `kakaobank`.`NATN_MASTER` (`NATN_CODE`, `STATE_CODE`, `NATN_NAME`, `STATE_NM`) VALUES ('USA', 'NY', '미국', '뉴욕');

INSERT INTO `kakaobank`.`EXCHANGE_RATE_TRAN` (`PROC_YMD`, `PROC_SEQ`, `CURR_CODE`, `BUY_RATE`, `SELL_RATE`, `BASE_RATE`) VALUES ('20210321', '1', 'USD', '1000', '1200', '1100');

INSERT INTO `kakaobank`.`DEAL_FEE_MASTER` (`TRNS_BASE_CODE`, `SECTION_BASE_AMT`, `CURR_CODE`, `FEE_AMT`) VALUES ('01', '0', 'USD', '5');
INSERT INTO `kakaobank`.`DEAL_FEE_MASTER` (`TRNS_BASE_CODE`, `SECTION_BASE_AMT`, `CURR_CODE`, `FEE_AMT`) VALUES ('02', '0', 'KRW', '5000');
INSERT INTO `kakaobank`.`DEAL_FEE_MASTER` (`TRNS_BASE_CODE`, `SECTION_BASE_AMT`, `CURR_CODE`, `FEE_AMT`) VALUES ('02', '50000000', 'KRW', ‘10000');

INSERT INTO `kakaobank`.`DEAL_LIMIT_MASTER` (`TRNS_BASE_CODE`, `CURR_CODE`, `EXCPT_YN`, `TRNS_LIM_AMT`) VALUES ('01', 'USD', 'N', '5000');
INSERT INTO `kakaobank`.`DEAL_LIMIT_MASTER` (`TRNS_BASE_CODE`, `CURR_CODE`, `EXCPT_YN`, `TRNS_LIM_AMT`) VALUES ('01', 'USD', 'Y', '50000');
INSERT INTO `kakaobank`.`DEAL_LIMIT_MASTER` (`TRNS_BASE_CODE`, `CURR_CODE`, `EXCPT_YN`, `TRNS_LIM_AMT`) VALUES ('02', 'USD', 'N', '5000');
INSERT INTO `kakaobank`.`DEAL_LIMIT_MASTER` (`TRNS_BASE_CODE`, `CURR_CODE`, `EXCPT_YN`, `TRNS_LIM_AMT`) VALUES ('02', 'USD', 'Y', '50000');

INSERT INTO `kakaobank`.`BSNS_RMRK_MASTER` (`BSNS_RMRK_CODE`, `BSNS_RMRK_NM`) VALUES ('001', '입금');
INSERT INTO `kakaobank`.`BSNS_RMRK_MASTER` (`BSNS_RMRK_CODE`, `BSNS_RMRK_NM`) VALUES ('002', '출금');
INSERT INTO `kakaobank`.`BSNS_RMRK_MASTER` (`BSNS_RMRK_CODE`, `BSNS_RMRK_NM`) VALUES ('003', '해외입금');
INSERT INTO `kakaobank`.`BSNS_RMRK_MASTER` (`BSNS_RMRK_CODE`, `BSNS_RMRK_NM`) VALUES ('004', '해외출금');
INSERT INTO `kakaobank`.`BSNS_RMRK_MASTER` (`BSNS_RMRK_CODE`, `BSNS_RMRK_NM`) VALUES ('005', '해외WU출금');

